wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 15
hidden_size:
  value: 128
learning_rate:
  value: 0.0005290751033246231
loss:
  value: mse
num_layers:
  value: 4
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: random
