wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 15
hidden_size:
  value: 128
learning_rate:
  value: 0.004828742137915539
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: rmsprop
weight_decay:
  value: 0.001
weight_init:
  value: xavier
