wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 15
hidden_size:
  value: 64
learning_rate:
  value: 0.0004117012661205671
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: nag
weight_decay:
  value: 0
weight_init:
  value: xavier
